### PR TITLE
Making gem developer-friendly.

### PR DESCRIPTION
**Pull request by oruen**
This is my attempt on easing gem development setup. I've switched from Bones to Bundler, fixed .gemspec file to include proper gem dependencies and replaced version class method with VERSION constant.

Gem is now easier to start developing on and more spec-friendly.

### CODE REVIEW

**Comment by andrewvc** [comment]
This all looks fantastic. Bones is actually kind of irritating to work with, good call! So, I've given you collaborator access, in light of all the great patches.

Feel free to push directly to andrewvc/em-zeromq!

**Comment by schmurfy** [comment]
That is a little odd to have em-zeromq depends on ffi don't you think ? It is ffi-rzmq which depends on ffi not em-zeromq.
The dependency problem was one of the things I asked andrewc about but the problem is not only jruby but rubinius too, and an even greater problem is that you need a recent version of the ffi gem to support blocking calls without triggering the GIL but ffi do not expose any version :(

**Comment by andrewvc** [comment]
schmurfy, you're completely right, I should put ffi into ffi-rzmq. I wasn't actually aware of how to do this before actually, I didn't realize that by using bundler you could conditionally require ffi for say 1.9.2 but exclude it for rubinius. 

I didn't realize ffi didn't expose a version. How is that possible schmurfy? I think the currently released gems are fine, I don't think you need the git version anymore, unless I'm mistaken.

**Comment by schmurfy** [comment]
I did not know either we could specify requirements only for a specific platform in the gemspec file.
It is true that if the ffir-rzmq gem can depends on a specific version of the ffi gem it solves all our problems since the gem will no longer work with outdated ffi.

The version not exposed I was talking about is in the ffi gem code, there is not FFI::VERSION or equivalent to check against but adding the dependency in the gemspec for MRI platform solve the problem better if we can do that.

**Comment by oruen** [comment]
I've figured out the way I did conditional dependency in the patch is the wrong way. Different platforms should have gems with different deps. The way it's done in `buildr` https://github.com/apache/buildr/blob/trunk/buildr.gemspec is how it should be done. Buildr has different gems for java, win and ruby platforms - I'm going to stay this way in the very next commit to em-zeromq and dripdrop.

**Comment by andrewvc** [comment]
Great! I just removed the ffi dep from em-zeromq btw. This will be great for dripdrop because it'll let me include eventmachine_httpserver as a dep for non-jruby platforms. 

However, I don't think em-zeromq needs platform deps, it's only deps are eventmachine and ffi-rzmq. ffi-rzmq really needs to handle the 'ffi' issue however. Of course rbx and 1.9.2 are considered the same platform I believe, which is problematic.

**Pull request merged**
